-- materialticket schema is managed by Prisma, not this file.
--
-- The authoritative schema lives in backend/prisma/schema.prisma and is applied
-- with `npx prisma db push` (dev) or `prisma migrate` (stable). Postgres-specific
-- extras (full-text index, partial indexes) are ensured at boot by
-- backend/src/db/pgExtras.ts.
--
-- This file is only a mount point for the Postgres init dir; add seed data below
-- if you need it. (The previous hand-written MySQL DDL was removed in 1.1.0 — it
-- was MariaDB-only and predated the auth/session tables.)
SELECT 1;
